# Generated by Django 2.2 on 2019-05-13 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20190513_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cType',
            new_name='categoryType',
        ),
    ]
