# Generated by Django 2.2 on 2019-05-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20190513_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryType',
            new_name='type',
        ),
    ]
