# Generated by Django 2.1 on 2018-08-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_categorytranslation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'permissions': (('list_category', 'Can list category'), ('retrieve_category', 'Can retrieve category'), ('delete_list_category', 'Can delete list category'), ('change_translation_category', 'Can change translation category'))},
        ),
    ]
