# Generated by Django 2.2.4 on 2019-09-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'banks',
                'ordering': ['-id'],
            },
        ),
    ]
