# Generated by Django 2.2 on 2019-05-12 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('count_check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countcheck',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='area_count_checks', to='area.Area'),
            preserve_default=False,
        ),
    ]
