# Generated by Django 2.2 on 2019-05-12 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('count_check', '0002_countcheck_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countcheck',
            name='area',
        ),
    ]
