# Generated by Django 2.1.7 on 2019-03-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='lock',
            field=models.BooleanField(default=False),
        ),
    ]
