# Generated by Django 2.1.7 on 2019-03-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_administrator_lock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='lock',
            new_name='is_lock',
        ),
        migrations.AddField(
            model_name='administrator',
            name='is_cust_care',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='administrator',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
    ]
