# Generated by Django 2.1.7 on 2019-02-24 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_auto_20190224_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'ordering': ['-id']},
        ),
    ]
