# Generated by Django 2.2.5 on 2019-09-15 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0003_customer_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=128)),
                ('account_name', models.CharField(max_length=128)),
                ('account_number', models.CharField(max_length=60)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_banks', to='customer.Customer')),
            ],
            options={
                'db_table': 'customer_banks',
                'ordering': ['-id'],
            },
        ),
    ]
