# Generated by Django 2.2 on 2019-05-04 14:13

from django.db import migrations, models
import django.db.models.deletion
import utils.helpers.tools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0005_auto_20190504_2054'),
        ('address', '0002_auto_20190406_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(max_length=60, unique=True)),
                ('packages', models.IntegerField(default=0)),
                ('purchase_code', models.CharField(blank=True, max_length=60)),
                ('address_code', models.CharField(blank=True, max_length=60)),
                ('landing_status', models.IntegerField(choices=[(utils.helpers.tools.LandingStatus(1), 'Mới'), (utils.helpers.tools.LandingStatus(2), 'Về TQ'), (utils.helpers.tools.LandingStatus(3), 'Về VN'), (utils.helpers.tools.LandingStatus(4), 'Đã xuất')], default=1)),
                ('cn_date', models.DateTimeField(null=True)),
                ('vn_date', models.DateTimeField(null=True)),
                ('exported_date', models.DateTimeField(null=True)),
                ('mass_convert_factor', models.IntegerField(default=6000)),
                ('input_mass', models.FloatField(default=0)),
                ('convert_mass', models.FloatField(default=0)),
                ('convert_volume', models.FloatField(default=0)),
                ('length', models.FloatField(default=0)),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('wooden_box', models.BooleanField(default=False)),
                ('shockproof', models.BooleanField(default=False)),
                ('insurance_register', models.BooleanField(default=False)),
                ('insurance_value', models.FloatField(default=0)),
                ('insurance_note', models.CharField(blank=True, max_length=250)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_bols', to='address.Address')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_bols', to='customer.Customer')),
            ],
            options={
                'db_table': 'bols',
                'ordering': ['-id'],
            },
        ),
    ]
