# Generated by Django 2.2 on 2019-05-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bol',
            name='delivery_fee_mass_unit_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bol',
            name='delivery_fee_volume_unit_price',
            field=models.IntegerField(default=0),
        ),
    ]
