# Generated by Django 2.2 on 2019-05-05 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('bol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bol',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_bols', to='order.Order'),
        ),
    ]
