# Generated by Django 2.2 on 2019-05-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0002_bol_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bol',
            name='cny_shockproof_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bol',
            name='cny_wooden_box_fee',
            field=models.FloatField(default=0),
        ),
    ]
