# Generated by Django 2.2.3 on 2019-07-14 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bol', '0002_bol_customer'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bol',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_bols', to='order.Order'),
        ),
    ]
