# Generated by Django 2.2 on 2019-05-04 14:56

from django.db import migrations, models
import utils.helpers.tools


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0002_auto_20190504_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='bol',
            name='delivery_fee_type',
            field=models.IntegerField(choices=[(utils.helpers.tools.DeliveryFeeType(1), 'Max lợi nhuận'), (utils.helpers.tools.DeliveryFeeType(2), 'Thang khối lượng'), (utils.helpers.tools.DeliveryFeeType(3), 'Đơn giá khối lượng'), (utils.helpers.tools.DeliveryFeeType(4), 'Đơn giá mét khối')], default=1),
        ),
    ]
