# Generated by Django 2.2.3 on 2019-07-19 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0003_bol_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bol',
            options={'ordering': ['-id'], 'permissions': (('get_order_items_for_checking_bol', 'Can get order items for checking from bol'), ('change_bag_order', 'Can change bag'))},
        ),
    ]
