# Generated by Django 2.2 on 2019-05-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0003_auto_20190505_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='bol',
            name='cny_sub_fee',
            field=models.FloatField(default=0),
        ),
    ]
