# Generated by Django 2.2.2 on 2019-06-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0003_bol_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bol',
            name='cny_sub_fee',
            field=models.FloatField(default=0),
        ),
    ]
