# Generated by Django 2.2 on 2019-05-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0004_bol_cny_sub_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bol',
            old_name='input_mass',
            new_name='mass',
        ),
        migrations.RenameField(
            model_name='bol',
            old_name='delivery_fee_mass_unit_price',
            new_name='mass_unit_price',
        ),
        migrations.RenameField(
            model_name='bol',
            old_name='delivery_fee_volume_unit_price',
            new_name='volume_unit_price',
        ),
        migrations.RemoveField(
            model_name='bol',
            name='convert_mass',
        ),
        migrations.RemoveField(
            model_name='bol',
            name='convert_volume',
        ),
        migrations.AddField(
            model_name='bol',
            name='delivery_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bol',
            name='mass_range_unit_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bol',
            name='volume_range_unit_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bol',
            name='delivery_fee_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Max lợi nhuận'), (2, 'Thang khối lượng'), (3, 'Đơn giá khối lượng'), (4, 'Khối lượng quy đổi'), (5, 'Thang mét khối'), (6, 'Đơn giá mét khối')]),
        ),
    ]
