# Generated by Django 2.2 on 2019-05-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0005_auto_20190512_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bol',
            name='delivery_fee_type',
            field=models.IntegerField(choices=[(0, 'Chưa xác định'), (1, 'Max lợi nhuận'), (2, 'Thang khối lượng'), (3, 'Đơn giá khối lượng'), (4, 'Khối lượng quy đổi'), (5, 'Thang mét khối'), (6, 'Đơn giá mét khối')], default=0),
        ),
    ]
