# Generated by Django 2.2.3 on 2019-07-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0006_auto_20190707_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='BolDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'bol_dates',
                'ordering': ['-date'],
            },
        ),
    ]
