# Generated by Django 2.2 on 2019-05-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0006_auto_20190513_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bol',
            name='cny_sub_fee',
        ),
    ]
