# Generated by Django 2.2.1 on 2019-05-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0007_remove_bol_cny_sub_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bol',
            name='packages',
            field=models.IntegerField(default=1),
        ),
    ]
