# Generated by Django 2.2.3 on 2019-07-10 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0008_auto_20190710_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='bol',
            name='bol_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='date_bols', to='bol.BolDate'),
        ),
    ]
