# Generated by Django 2.2.2 on 2019-06-04 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0008_auto_20190520_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bol',
            old_name='insurance_register',
            new_name='insurance',
        ),
    ]
