# Generated by Django 2.2.3 on 2019-07-27 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0008_auto_20190727_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bol',
            name='checked',
        ),
    ]
