# Generated by Django 2.2.2 on 2019-06-04 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0009_auto_20190604_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bol',
            old_name='insurance_value',
            new_name='cny_insurance_value',
        ),
    ]
