# Generated by Django 2.2.3 on 2019-07-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0010_auto_20190710_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boldate',
            name='date_str',
            field=models.CharField(max_length=32),
        ),
    ]
