# Generated by Django 2.2.2 on 2019-06-06 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0010_auto_20190604_0718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bol',
            old_name='insurance_note',
            new_name='note',
        ),
    ]
