# Generated by Django 2.2.3 on 2019-07-10 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0012_bag'),
    ]

    operations = [
        migrations.AddField(
            model_name='bol',
            name='bag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bag_bols', to='bol.Bag'),
        ),
    ]
