# Generated by Django 2.2.3 on 2019-07-14 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('bol', '0013_bol_bag'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_bags', to='area.Area'),
        ),
    ]
