# Generated by Django 2.2.3 on 2019-08-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0014_auto_20190804_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='bol',
            name='rate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bol',
            name='real_rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
