# Generated by Django 2.2.3 on 2019-07-14 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0014_bag_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bag',
            old_name='title',
            new_name='uid',
        ),
        migrations.AddField(
            model_name='bag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
