# Generated by Django 2.2.4 on 2019-08-10 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('bol', '0016_auto_20190804_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='bol',
            name='exporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_bols', to='staff.Staff'),
        ),
    ]
