# Generated by Django 2.2.4 on 2019-09-03 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0019_bol_cny_insurance_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bol',
            name='receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_bols', to='receipt.Receipt'),
        ),
    ]
