# Generated by Django 2.2.5 on 2019-09-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0021_bol_count_check'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bol',
            options={'ordering': ['-id'], 'permissions': (('change_bag_bol', 'Can change bag'), ('get_date_bol', 'Can get date'), ('match_vn_bol', 'Can get match VN bol'), ('ready_to_export_list_bol', 'Can get bol to export'), ('export_bol', 'Can export'), ('export_check_bol', 'Can check before export'), ('mark_cn_bol', 'Can mark bol arrived to CN store'), ('unmark_cn_bol', 'Can unmark bol arrived to CN store'))},
        ),
    ]
