# Generated by Django 2.2.6 on 2019-10-20 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0022_auto_20190916_0656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bol',
            options={'ordering': ['-id'], 'permissions': (('change_bag_bol', 'Can change bag'), ('get_date_bol', 'Can get date'), ('match_vn_bol', 'Can get match VN bol'), ('ready_to_export_list_bol', 'Can get bol to export'), ('export_bol', 'Can export'), ('export_check_bol', 'Can check before export'), ('mark_cn_bol', 'Can mark bol arrived to CN store'), ('mark_cn_by_uploading_bol', 'Can mark bol arrived to CN store by uploading'), ('unmark_cn_bol', 'Can unmark bol arrived to CN store'))},
        ),
    ]
