# Generated by Django 2.2.6 on 2019-10-27 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0023_auto_20191020_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bol',
            options={'ordering': ['-id'], 'permissions': (('change_bag_bol', 'Đổi bao hàng'), ('get_date_bol', 'Xem danh sách theo ngày'), ('match_vn_bol', 'Bắn vận đơn VN'), ('ready_to_export_list_bol', 'Xem danh sách vận đơn sẵn sàng xuất'), ('export_bol', 'Xuất vận đơn'), ('export_check_bol', 'Kiểm tra vận đơn trước khi xuất'), ('mark_cn_bol', 'Bắn vận đơn TQ'), ('mark_cn_by_uploading_bol', 'Upload vận đơn TQ bằng excel'), ('unmark_cn_bol', 'Bỏ trạng thái vận đơn TQ'))},
        ),
    ]
