# Generated by Django 2.2.5 on 2019-09-15 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('bag', '0003_bag_bol_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_bags', to='staff.Staff'),
        ),
    ]
