# Generated by Django 2.2 on 2019-04-26 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0005_auto_20190426_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('shop_link', models.CharField(blank=True, max_length=250)),
                ('shop_nick', models.CharField(max_length=250)),
                ('site', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=500)),
                ('size', models.CharField(blank=True, max_length=500)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.FloatField(default=0)),
                ('note', models.TextField(blank=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='order.Order')),
            ],
            options={
                'db_table': 'order_items',
                'ordering': ['-id'],
            },
        ),
    ]
