# Generated by Django 2.2.2 on 2019-06-08 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('color', models.CharField(blank=True, max_length=500)),
                ('size', models.CharField(blank=True, max_length=500)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.FloatField(default=0)),
                ('note', models.TextField(blank=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='order.Order')),
            ],
            options={
                'db_table': 'order_items',
                'ordering': ['-id'],
                'permissions': (('change_color_orderitem', 'Can change color'), ('change_size_orderitem', 'Can change size'), ('change_quantity_orderitem', 'Can change quantity'), ('change_unit_price_orderitem', 'Can change unit price'), ('change_note_orderitem', 'Can change note')),
            },
        ),
    ]
