# Generated by Django 2.2 on 2019-04-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shop_link',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='shop_nick',
        ),
    ]
