# Generated by Django 2.2.1 on 2019-05-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-id'], 'permissions': (('change_color_orderitem', 'Can change color'), ('change_size_orderitem', 'Can change size'), ('change_quantity_orderitem', 'Can change quantity'), ('change_unit_price_orderitem', 'Can change unit price'), ('change_note_orderitem', 'Can change note'))},
        ),
    ]
