# Generated by Django 2.2 on 2019-04-29 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_item', '0002_auto_20190429_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='site',
        ),
    ]
