# Generated by Django 2.2.3 on 2019-07-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_item', '0002_auto_20190612_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='checked_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
