# Generated by Django 2.2.2 on 2019-06-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.IntegerField()),
                ('sub_delta', models.IntegerField()),
                ('order_delta', models.IntegerField()),
            ],
            options={
                'db_table': 'rates',
                'ordering': ['-id'],
            },
        ),
    ]
