# Generated by Django 2.2 on 2019-05-17 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='order_rate',
            new_name='order_deta',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='buy_rate',
            new_name='sub_delta',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='sell_rate',
        ),
    ]
