# Generated by Django 2.2 on 2019-05-12 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('delivery_fee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryfee',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='area_delivery_fees', to='area.Area'),
            preserve_default=False,
        ),
    ]
