# Generated by Django 2.2 on 2019-05-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_fee', '0002_deliveryfee_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryfee',
            options={'ordering': ['-stop']},
        ),
        migrations.RenameField(
            model_name='deliveryfee',
            old_name='fee',
            new_name='vnd_unit_price',
        ),
        migrations.RemoveField(
            model_name='deliveryfee',
            name='from_mass',
        ),
        migrations.RemoveField(
            model_name='deliveryfee',
            name='to_mass',
        ),
        migrations.AddField(
            model_name='deliveryfee',
            name='start',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryfee',
            name='stop',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryfee',
            name='type',
            field=models.IntegerField(choices=[(1, 'MASS'), (2, 'VOLUME')], default=1),
        ),
    ]
