# Generated by Django 2.2 on 2019-05-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_fee', '0003_auto_20190512_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryfee',
            name='type',
            field=models.IntegerField(choices=[(1, 'Mass'), (2, 'Volume')], default=1),
        ),
    ]
