# Generated by Django 2.2.3 on 2019-08-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='vnd_total',
            field=models.IntegerField(default=0),
        ),
    ]
