# Generated by Django 2.2.3 on 2019-08-03 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_address_customer'),
        ('receipt', '0002_receipt_vnd_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='address_receipts', to='address.Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='address_code',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
