# Generated by Django 2.2.3 on 2019-08-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0003_auto_20190803_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='vnd_sub_fee',
            new_name='vnd_other_sub_fee',
        ),
    ]
