# Generated by Django 2.2.3 on 2019-08-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0005_remove_receipt_vnd_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='vnd_total',
            field=models.IntegerField(default=0),
        ),
    ]
