# Generated by Django 2.2.4 on 2019-09-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0007_auto_20190810_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-id'], 'permissions': (('retrieve_to_print', 'Can print receipt'),)},
        ),
    ]
