# Generated by Django 2.2.6 on 2019-10-27 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0008_auto_20190902_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-id'], 'permissions': (('retrieve_to_print', 'In'),)},
        ),
    ]
