# Generated by Django 2.2 on 2019-04-05 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=250, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('phone', models.CharField(blank=True, max_length=250)),
                ('fullname', models.CharField(blank=True, max_length=250)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area', to='area.Area')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='customer.Customer')),
            ],
            options={
                'db_table': 'addresses',
                'ordering': ['-id'],
            },
        ),
    ]
