# Generated by Django 2.2 on 2019-04-06 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='area_id',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
