# Generated by Django 2.2.2 on 2019-06-08 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, unique=True)),
                ('content', models.TextField()),
                ('uid', models.CharField(max_length=250, unique=True)),
                ('slug', models.CharField(blank=True, max_length=250)),
                ('category', models.ForeignKey(limit_choices_to={'type': 'article'}, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='category.Category')),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['-id'],
            },
        ),
    ]
