# Generated by Django 2.1.7 on 2019-02-24 08:22

import apps.article.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=36)),
                ('slug', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=apps.article.models.image_destination)),
                ('content', models.TextField(blank=True)),
                ('use_slide', models.BooleanField(default=False)),
                ('pin', models.BooleanField(default=False)),
                ('thumbnail_in_content', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_articles', to='article.Article')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='category.Category')),
                ('tags', models.ManyToManyField(to='tag.Tag')),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='ArticleTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_translations', to='article.Article')),
            ],
            options={
                'db_table': 'article_translations',
                'ordering': ['-id'],
                'default_permissions': (),
            },
        ),
    ]
