# Generated by Django 2.1.7 on 2019-02-24 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_auto_20180802_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-order']},
        ),
    ]
