# Generated by Django 2.2.2 on 2019-06-08 09:05

import apps.customer.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(blank=True, max_length=250)),
                ('reset_password_token', models.CharField(blank=True, max_length=250)),
                ('reset_password_tmp', models.CharField(blank=True, max_length=250)),
                ('reset_password_created', models.DateTimeField(blank=True, null=True)),
                ('signup_token', models.CharField(blank=True, max_length=250)),
                ('signup_token_created', models.DateTimeField(blank=True, null=True)),
                ('phone', models.CharField(max_length=32)),
                ('company', models.CharField(blank=True, max_length=256)),
                ('order_fee_factor', models.FloatField(default=10)),
                ('delivery_fee_mass_unit_price', models.IntegerField(default=0)),
                ('delivery_fee_volume_unit_price', models.IntegerField(default=0)),
                ('deposit_factor', models.FloatField(default=50)),
                ('complaint_days', models.IntegerField(default=2)),
                ('is_lock', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, upload_to=apps.customer.models.imgDest)),
                ('shopping_cart', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['-user'],
            },
        ),
    ]
