# Generated by Django 2.2 on 2019-04-06 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cust_care_id',
            new_name='cust_care',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='sale_id',
            new_name='sale',
        ),
    ]
