# Generated by Django 2.1.7 on 2019-03-31 08:20

import apps.customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=apps.customer.models.imgDest),
        ),
    ]
