# Generated by Django 2.1.7 on 2019-03-30 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_auto_20190329_0611'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_care_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cust_care', to='administrator.Administrator'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='sale_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale', to='administrator.Administrator'),
        ),
    ]
