# Generated by Django 2.2 on 2019-04-21 05:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20190406_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shopping_cart',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
