# Generated by Django 2.2.5 on 2019-09-28 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_group', '0001_initial'),
        ('customer', '0003_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_group', to='customer_group.CustomerGroup'),
        ),
    ]
