# Generated by Django 2.2 on 2019-04-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_shopping_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='complaint_days',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='customer',
            name='delivery_fee_unit_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='deposit_factor',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='order_fee_factor',
            field=models.FloatField(default=10),
        ),
    ]
