# Generated by Django 2.2 on 2019-05-05 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop_link', models.CharField(max_length=250)),
                ('shop_nick', models.CharField(blank=True, max_length=250)),
                ('site', models.CharField(max_length=50)),
                ('count_check', models.BooleanField(default=False)),
                ('wooden_box', models.BooleanField(default=False)),
                ('shockproof', models.BooleanField(default=False)),
                ('approved_date', models.DateTimeField(null=True)),
                ('rate', models.IntegerField()),
                ('real_rate', models.IntegerField()),
                ('cny_amount', models.FloatField(default=0)),
                ('cny_inland_delivery_fee', models.FloatField(default=0)),
                ('cny_sub_fee', models.FloatField(default=0)),
                ('cny_insurance_fee', models.FloatField(default=0)),
                ('vnd_delivery_fee', models.IntegerField(default=0)),
                ('vnd_sub_fee', models.IntegerField(default=0)),
                ('order_fee_factor', models.FloatField(default=0)),
                ('order_fee_factor_fixed', models.FloatField(default=0)),
                ('deposit_factor', models.FloatField(default=0)),
                ('mass', models.FloatField(default=0)),
                ('packages', models.IntegerField(default=0)),
                ('number_of_bol', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('status', models.IntegerField(choices=[(1, 'Chờ duyệt'), (2, 'Đã duyệt'), (3, 'Chờ thanh toán'), (4, 'Đã thanh toán'), (5, 'Đã phát hàng'), (6, 'Về kho TQ'), (7, 'Về kho VN'), (8, 'Đã xuất hàng'), (9, 'Hoàn thành'), (10, 'Huỷ')], default=1)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='address.Address')),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_orders', to='staff.Staff')),
                ('cust_care', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cust_care_orders', to='staff.Staff')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-id'],
            },
        ),
    ]
