# Generated by Django 2.2.2 on 2019-06-08 09:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_address_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.CharField(blank=True, max_length=500)),
                ('shop_link', models.CharField(max_length=250)),
                ('shop_nick', models.CharField(blank=True, max_length=250)),
                ('site', models.CharField(max_length=50)),
                ('count_check', models.BooleanField(default=False)),
                ('wooden_box', models.BooleanField(default=False)),
                ('shockproof', models.BooleanField(default=False)),
                ('count_check_fee_input', models.FloatField(default=0)),
                ('approved_date', models.DateTimeField(null=True)),
                ('rate', models.PositiveIntegerField()),
                ('real_rate', models.PositiveIntegerField()),
                ('cny_amount', models.FloatField(default=0)),
                ('cny_order_fee', models.FloatField(default=0)),
                ('cny_inland_delivery_fee', models.FloatField(default=0)),
                ('cny_count_check_fee', models.FloatField(default=0)),
                ('cny_shockproof_fee', models.FloatField(default=0)),
                ('cny_wooden_box_fee', models.FloatField(default=0)),
                ('vnd_delivery_fee', models.PositiveIntegerField(default=0)),
                ('vnd_sub_fee', models.PositiveIntegerField(default=0)),
                ('vnd_paid', models.PositiveIntegerField(default=0)),
                ('vnd_delivery_fee_discount', models.PositiveIntegerField(default=0)),
                ('cny_order_fee_discount', models.FloatField(default=0)),
                ('cny_count_check_fee_discount', models.FloatField(default=0)),
                ('order_fee_factor', models.FloatField(default=0)),
                ('deposit_factor', models.FloatField(default=0)),
                ('mass', models.FloatField(default=0)),
                ('packages', models.PositiveIntegerField(default=0)),
                ('number_of_bol', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('statistics', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Chờ duyệt'), (2, 'Đã duyệt'), (3, 'Chờ thanh toán'), (4, 'Đã thanh toán'), (5, 'Đã phát hàng'), (6, 'Về kho TQ'), (7, 'Về kho VN'), (8, 'Đã xuất hàng'), (9, 'Hoàn thành'), (10, 'Huỷ')], default=1)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='address_orders', to='address.Address')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-id'],
                'permissions': (('change_sale_order', 'Can change sale'), ('change_cust_care_order', 'Can change customer care'), ('change_rate_order', 'Can change rate'), ('change_address_order', 'Can change address'), ('change_voucher_order', 'Can change voucher'), ('change_count_check_fee_input_order', 'Can change count check fee'), ('change_cny_inland_delivery_fee_order', 'Can change inland delivery fee'), ('change_order_fee_factor_order', 'Can change order fee factor')),
            },
        ),
    ]
