# Generated by Django 2.2 on 2019-04-26 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_auto_20190406_1427'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_date', models.DateTimeField(null=True)),
                ('rate', models.IntegerField()),
                ('real_rate', models.IntegerField()),
                ('cny_amount', models.FloatField(default=0)),
                ('cny_order_fee', models.FloatField(default=0)),
                ('cny_inland_delivery_fee', models.FloatField(default=0)),
                ('cny_sub_fee', models.FloatField(default=0)),
                ('cny_insurance_fee', models.FloatField(default=0)),
                ('vnd_delivery_fee', models.IntegerField(default=0)),
                ('vnd_sub_fee', models.IntegerField(default=0)),
                ('order_fee_factor', models.FloatField(default=0)),
                ('deposit_factor', models.FloatField(default=0)),
                ('mass', models.FloatField(default=0)),
                ('packages', models.IntegerField(default=0)),
                ('number_of_bol', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(default='new', max_length=50)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='address.Address')),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_approver', to='staff.Staff')),
                ('cust_care', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_cust_care', to='staff.Staff')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-id'],
            },
        ),
    ]
