# Generated by Django 2.2.3 on 2019-07-14 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('customer', '0002_auto_20190714_1621'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_orders', to='staff.Staff'),
        ),
        migrations.AddField(
            model_name='order',
            name='checker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checker_orders', to='staff.Staff'),
        ),
        migrations.AddField(
            model_name='order',
            name='cust_care',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cust_care_orders', to='staff.Staff'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_orders', to='staff.Staff'),
        ),
    ]
