# Generated by Django 2.2 on 2019-05-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='count_check_fee_input',
            field=models.FloatField(default=0),
        ),
    ]
