# Generated by Django 2.2 on 2019-04-26 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cny_order_fee',
        ),
    ]
