# Generated by Django 2.2 on 2019-05-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_count_check_fee_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cny_count_check_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='cny_shockproof_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='cny_wooden_box_fee',
            field=models.FloatField(default=0),
        ),
    ]
