# Generated by Django 2.2.2 on 2019-06-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190608_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uid',
            field=models.CharField(default='1HN008F1', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
