# Generated by Django 2.2 on 2019-04-26 08:36

from django.db import migrations, models
import utils.helpers.tools


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190426_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(utils.helpers.tools.OrderStatus(1), 'Chờ duyệt'), (utils.helpers.tools.OrderStatus(2), 'Đã duyệt'), (utils.helpers.tools.OrderStatus(3), 'Chờ thanh toán'), (utils.helpers.tools.OrderStatus(4), 'Đã thanh toán'), (utils.helpers.tools.OrderStatus(5), 'Đã phát hàng'), (utils.helpers.tools.OrderStatus(6), 'Về kho TQ'), (utils.helpers.tools.OrderStatus(7), 'Về kho VN'), (utils.helpers.tools.OrderStatus(8), 'Đã xuất hàng'), (utils.helpers.tools.OrderStatus(9), 'Hoàn thành'), (utils.helpers.tools.OrderStatus(10), 'Huỷ')], default=1),
        ),
    ]
