# Generated by Django 2.2 on 2019-05-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190505_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cny_sub_fee',
        ),
    ]
