# Generated by Django 2.2.2 on 2019-06-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchase_code',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
