# Generated by Django 2.2 on 2019-04-26 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190426_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_orders', to='staff.Staff'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cust_care',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cust_care_orders', to='staff.Staff'),
        ),
    ]
