# Generated by Django 2.2 on 2019-05-10 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_cny_sub_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cny_insurance_fee',
        ),
    ]
