# Generated by Django 2.2 on 2019-05-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_cny_insurance_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cny_order_fee',
            field=models.FloatField(default=0),
        ),
    ]
