# Generated by Django 2.2 on 2019-04-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190426_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shop_link',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shop_nick',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
