# Generated by Django 2.2.3 on 2019-07-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190728_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='potential_bols',
            field=models.TextField(blank=True),
        ),
    ]
