# Generated by Django 2.2.1 on 2019-05-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_cny_order_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
