# Generated by Django 2.2 on 2019-05-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_cny_order_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uid',
            field=models.CharField(max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
