# Generated by Django 2.2 on 2019-04-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20190429_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='site',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
