# Generated by Django 2.2 on 2019-04-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='count_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shockproof',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='wooden_box',
            field=models.BooleanField(default=False),
        ),
    ]
