# Generated by Django 2.2.4 on 2019-08-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deposit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
