# Generated by Django 2.2 on 2019-05-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
