# Generated by Django 2.2.1 on 2019-05-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
