# Generated by Django 2.2.2 on 2019-06-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20190611_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cny_sub_fee',
            field=models.FloatField(default=0),
        ),
    ]
