# Generated by Django 2.2.1 on 2019-05-19 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20190508_1939'),
        ('order', '0008_auto_20190519_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_orders', to='staff.Staff'),
        ),
    ]
