# Generated by Django 2.2.3 on 2019-07-04 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('order', '0008_order_cny_sub_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checked_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='checker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checker_orders', to='staff.Staff'),
        ),
    ]
