# Generated by Django 2.2 on 2019-05-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20190430_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_fee_factor_static',
            field=models.FloatField(default=0),
        ),
    ]
