# Generated by Django 2.2.1 on 2019-05-19 16:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='statistics',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
