# Generated by Django 2.2 on 2019-05-04 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_order_fee_factor_static'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_fee_factor_static',
            new_name='order_fee_factor_fixed',
        ),
    ]
