# Generated by Django 2.2.1 on 2019-05-21 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20190508_1939'),
        ('order', '0010_order_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to='customer.Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='address_orders', to='address.Address'),
            preserve_default=False,
        ),
    ]
