# Generated by Django 2.2.5 on 2019-09-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_vnd_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='charge_remain',
            field=models.BooleanField(default=False),
        ),
    ]
