# Generated by Django 2.2.1 on 2019-05-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20190521_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id'], 'permissions': [('change_sale_order', 'Can change sale'), ('change_cust_care_order', 'Can change customer care')]},
        ),
    ]
