# Generated by Django 2.2.1 on 2019-05-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20190526_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cny_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='vnd_discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='vnd_paid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='number_of_bol',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='packages',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='rate',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='real_rate',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Chờ duyệt'), (2, 'Đã duyệt'), (3, 'Chờ thanh toán'), (4, 'Đã thanh toán'), (5, 'Đã phát hàng'), (6, 'Về kho TQ'), (7, 'Về kho VN'), (8, 'Đã xuất hàng'), (9, 'Hoàn thành'), (10, 'Huỷ')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='vnd_delivery_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='vnd_sub_fee',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
