# Generated by Django 2.2.1 on 2019-05-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20190526_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cny_discount',
            new_name='cny_count_check_fee_discount',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='vnd_discount',
            new_name='vnd_delivery_fee_discount',
        ),
        migrations.AddField(
            model_name='order',
            name='cny_order_fee_discount',
            field=models.FloatField(default=0),
        ),
    ]
