# Generated by Django 2.2.1 on 2019-05-26 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20190526_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_fee_factor_fixed',
        ),
    ]
