# Generated by Django 2.2.6 on 2019-10-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20191020_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cny_real_amount',
            field=models.FloatField(default=0),
        ),
    ]
