# Generated by Django 2.2.5 on 2019-09-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'customer_groups',
                'ordering': ['-id'],
            },
        ),
    ]
