# Generated by Django 2.2 on 2019-05-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_amount', models.IntegerField()),
                ('to_amount', models.IntegerField()),
                ('fee', models.FloatField()),
            ],
            options={
                'db_table': 'order_fees',
                'ordering': ['-to_amount'],
            },
        ),
    ]
