# Generated by Django 2.2.3 on 2019-07-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='customer_uid',
            new_name='customer_username',
        ),
        migrations.AddField(
            model_name='transaction',
            name='staff_username',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
