# Generated by Django 2.2.3 on 2019-07-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20190729_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='staff_username',
            field=models.CharField(max_length=64),
        ),
    ]
