# Generated by Django 2.2.3 on 2019-07-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20190729_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='money_type',
            field=models.IntegerField(choices=[(0, 'Gián tiếp'), (1, 'Tiền mặt'), (2, 'Chuyển khoản')]),
        ),
    ]
