# Generated by Django 2.2.3 on 2019-07-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20190729_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='staff_username',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
