# Generated by Django 2.2.3 on 2019-07-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20190729_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='assets',
            field=models.BooleanField(default=True),
        ),
    ]
