# Generated by Django 2.2.3 on 2019-07-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_transaction_assets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='assets',
            new_name='is_assets',
        ),
    ]
