# Generated by Django 2.2.3 on 2019-08-04 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0016_auto_20190804_1358'),
        ('transaction', '0008_transaction_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_transactions', to='bol.Bol'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bol_uid',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
