# Generated by Django 2.2.4 on 2019-09-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_transaction_bank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-id'], 'permissions': (('retrieve_to_print', 'Can print transaction'),)},
        ),
    ]
