# Generated by Django 2.2.5 on 2019-09-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_auto_20190902_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
