# Generated by Django 2.2.5 on 2019-09-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0014_transaction_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-id'], 'permissions': (('retrieve_to_print', 'Can print transaction'), ('get_total_statistics', 'Get total statistics'))},
        ),
    ]
