# Generated by Django 2.2.6 on 2019-10-27 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0016_auto_20190928_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-id'], 'permissions': (('retrieve_to_print', 'In'), ('get_total_statistics', 'Xem thống kê tổng'))},
        ),
    ]
