# Generated by Django 2.1.7 on 2019-02-24 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_auto_20180728_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'ordering': ['-id']},
        ),
    ]
