# Generated by Django 2.2 on 2019-04-05 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area_code', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(blank=True, max_length=250)),
                ('fullname', models.CharField(blank=True, max_length=250)),
                ('area_code_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_code', to='area_code.AreaCode')),
            ],
            options={
                'db_table': 'areas',
                'ordering': ['-id'],
            },
        ),
    ]
