# Generated by Django 2.1.7 on 2019-02-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('uid', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['-id'],
            },
        ),
    ]
