# Generated by Django 2.1.7 on 2019-02-24 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_auto_20180728_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-id']},
        ),
    ]
