# Generated by Django 2.1.7 on 2019-02-24 08:22

import apps.attach.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_uuid', models.CharField(max_length=36)),
                ('richtext_image', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=256)),
                ('filetype', models.CharField(default='image', max_length=32)),
                ('attachment', models.FileField(upload_to=apps.attach.models.file_destination)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'attaches',
                'ordering': ['-id'],
            },
        ),
    ]
