# Generated by Django 2.1.7 on 2019-02-24 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attach', '0006_auto_20180801_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attach',
            options={'ordering': ['-id']},
        ),
    ]
